config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :products
    resources :orders do 
      member do 
        post :cancel
        post :ship
        post :shipped
        post :return
      end  
    end 
  end

  namespace :account do
    resources :orders
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :items, controller: "cart_items"

  resources :carts do
    post "checkout",  on: :collection
    delete "clean",   on: :collection
  end

  resources :orders do
    member do
      get :pay_with_credit_card
      post :allpay_notify
    end
  end

  root "products#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM

  aasm do
    state :order_placed, :initial => true
    state :paid, :after_commit => :pay!
    event :make_payment do 
      transitions :from => :order_placed, :to => :paid
    end

    state :shipping
    event :ship do 
      transitions :form => :paid, :to => :shipping
    end

    state :shipped
    event :deliver do 
      transitions :from => :shipping, :to => :shipped
    end 

    state :order_cancelled
    event :cancell_order do 
      transitions :from => [:order_placed,:paid], :to => :order_cancelled
    end

    state :good_returned
    event :return_good do 
      transitions :form => [:shipped], :to => :good_returned
    end   
  end 

  belongs_to :user
  has_many :items, class_name: "OrderItem", dependent: :destroy
  has_one :info, class_name: "OrderInfo", dependent: :destroy

  accepts_nested_attributes_for :info

  scope :recent, -> { order("id DESC")}

  before_create :generate_token

  include Tokenable

  def calculate_total!(cart)
    self.total = cart.total_price
    self.save
  end

  def build_item_cache_from_cart(cart)
    cart.items.each do |cart_item|
      item = items.build
      item.product_name = cart_item.title
      item.quantity = cart.find_cart_item(cart_item).quantity
      item.price = cart_item.price
      item.save
    end
  end

  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true)
  end
end

app/controllers/account/orders_controller.rb
class Account::OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
  	@orders = current_user.orders.recent
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

  def index
  	@orders = Order.recent
  end

  def show
  	@order = Oder.find(params[:id])
  	@order_info = @order.info
  	@order_items = @order.items
  end

  def ship
    @order = Order.find(params[:id])
    @order.ship!
    redirect_to :back
  end

  def shipped
    @order = Order.find(params[:id])
    @order.deliver!
    redirect_to :back
  end

  def cancel
    @order = Order.find(params[:id])
    @order.cancell_order!
    redirect_to :back
  end

  def return
    @order = Order.find(params[:id])
    @order.return_good!
    redirect_to :back
  end



end

app/controllers/orders_controller.rb
class OrdersController < AdminController
  before_action :authenticate_user!, except: :allpay_notify
  protect_from_forgery except: :allpay_notify

  def allpay_notify
    order = Order.find_by_token(params[:id])
    type = params[:type]

    if params[:RtnCode] == "1"
      order.set_payment_with!(type)
      order.make_payment!
    end

    render text: '1|OK', status: 200
  end

  def create
    @order = current_user.orders.build(order_params)

    if @order.save
      OrderPlacingService.new(current_cart,@order).place_order!
    else
      render "carts/checkout"
    end
  end

  def show
    @order = Order.find_by_token(params[:id])
    @order_info = @order.info
    @order_items = @order.items
  end

  def pay_with_credit_card
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("credit_card")
    @order.make_pay!
    
    redirect_to account_orders_path, notice: "成功完成付款"
  end

  private

  def order_params
    params.require(:order).permit(info_attributes: [:billing_name,
                                                    :billing_address,
                                                    :shipping_name,
                                                    :shipping_address] )
  end
end

app/helpers/account/orders_helper.rb
module Account::OrdersHelper
  def render_payment_service_button(order, payment_type)
    payment_service_for order,
      order.user.email,
      service: :allpay,
      html: { authenticity_token: false, enforce_utf8: false, method: :post } do |service|

      service.merchant_trade_no   "#{order.id}s#{Time.now.strftime("%Y%m%d%H%M%S")}"
      service.merchant_trade_date order.created_at
      service.total_amount        order.total
      service.trade_desc          "order_sample"
      service.item_name           "order_sample"
      service.choose_payment      payment_gateway_type(payment_type)
      service.client_back_url     root_url
      service.return_url          allpay_notify_order_url(order.token, type: payment_type)
      service.encrypted_data

      submit_tag t("orders.payment_type.#{payment_type}") , name: nil, class: "btn btn-lg btn-danger btn-group"
    end
  end


  private

  def payment_gateway_type(payment_type)
    case payment_type
    when "credit_card"
      ActiveMerchant::Billing::Integrations::Allpay::PAYMENT_CREDIT_CARD
    when "cvs"
      ActiveMerchant::Billing::Integrations::Allpay::PAYMENT_CVS
    when "atm"
      ActiveMerchant::Billing::Integrations::Allpay::PAYMENT_ATM
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def render_order_timestamp(order)
  	order.created_at.to_s(:long)
  end

  def render_order_state(order)
  	t("orders.order_state.#{order.aasm_satte}")
  end

  def render_order_paid_state(order)
  	if order.paid? 
  		"已付款"
  	else 
  		"未付款"
  	end
  end
end

app/views/admin/orders/_state_option.html.erb
div style="padding:10px; float:right;">

  <% case order.aasm_state %>
  <% when "order_placed" %>
    <%= link_to("取消訂單", cancel_admin_order_path(order), class: "btn btn-default btn-sm", method: :post) %>

  <% when "paid" %>
    <%= link_to("取消訂單", cancel_admin_order_path(order), class: "btn btn-default btn-sm", method: :post) %>
    <%= link_to("出貨",ship_admin_order_path(order),class: "btn btn-default btn-sm", method: :post) %>

  <% when "shipping" %>
    <%= link_to("設為已出貨", shipped_admin_order_path(order), class: "btn btn-default btn-sm", method: :post) %>

  <% when "shipped" %>
    <%= link_to("退貨", return_admin_order_path(order), class: "btn btn-default btn-sm", method: :post) %>

  <% when "order_cancelled" %>
    <span class="label label-default">訂單已取消</span>

  <% when "good_returned" %>
    <span class="label label-default">已退貨</span>

  <% end %>

</div>

app/views/admin/orders/index.html.erb
<h2>訂單列表</h2>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>#</th>
			<th>生成時間</th>
			<th>訂購單</th>
			<th>訂單狀態</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= link_to( order.id , admin_order_path(order)) %></td>
			<td><%= render_order_timestamp(order) %></td>
			<td><%= order.user.email %></td>
			<td><%= render_order_state(order) %></td>
		</tr>
	</tbody>
</table>

app/views/admin/orders/show.html.erb
<div class="row">
   <div class="col-md-12">

    <h2> 訂單明細 (<%= render_order_paid_state(@order) %>) </h2>
    <%= render "/admin/orders/state_option", order: @order %>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="80%">商品明細</th>
          <th>單價</th>
          <th>數量</th>
        </tr>
      </thead>
      <tbody>

        <% @order_items.each do |order_item| %>
          <tr>
            <td>
              <%= order_item.product_name %>
            </td>
            <td>
              <%= order_item.price %>
            </td>
            <td>
              <%= order_item.quantity %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
       <span> 總計 <%= @order.total %> NTD
       </span>
     </div>

     <hr>

     <h2> 寄送資訊 </h2>

     <table class="table table-striped table-bordered">
      <tbody>
        <tr>
          <td>
            訂購人
          </td>
        </tr>
        <tr>
          <td>
            <%= @order_info.billing_name %> - <%= @order_info.billing_address %>
          </td>
        </tr>
        <tr>
          <td>
            訂購人
          </td>
        </tr>
        <tr>
          <td>
            <%= @order_info.billing_name %> - <%= @order_info.billing_address %>
          </td>
        </tr>
      </tbody>
    </table>

  </div>
</div>